### ISSUE TITLE
include/agon/vdp_vdu.h is much older than the same file in src/libc/include/vdp_vdu.h

### ISSUE THREAD

**Issue by bradleysmith** [pcawte/AgDev#23]
Is this intentional?

The invaders sprite demo (built locally) crashes on my emulator (real Agon here in a couple of days) and I wondered if this might be the reason why.

**Comment by BlastBrothers** [comment]
This should be resolved, now that the project directories have been cleaned up.

There's still the lingering problem of some example projects containing copies of AgDev files in their own folders - but that should take care of itself when #31 is completed.

**Comment by astralaster** [comment]
I will close this, because there is only one of the files left now. :)
