### ISSUE TITLE
Suggest bringing back directory read functions.

### ISSUE THREAD

**Issue by lennart-benschop** [pcawte/AgDev#35]
AgDev versions <2.0.0 contained two versions of mos_api.h
- One in include. It contains the ffs_dopen/ffs_dread/ffs_dclose functions. Plus some related structs.
- One in src/libc/include. It does NOT contain the directory stuff.

AgDev version 2.0.x dropped to include directory at the top-level of the project (which was a good thing I think), but thereby lost the directory related definitions in mos_api.h. Can they be brought back in the mos_api.h file that is still there?

**Comment by astralaster** [comment]
Fixed by #36
